Repository pluralsh/terraform-provider-plural, pull requests merged in 2024-06, with the labels that each got.

#35 Remove node pool/provider configuration
  build/install.sh
  internal/resource/cluster.go
  internal/resource/cluster_model.go
  internal/resource/cluster_schema.go
Labels: enhancement, hotfix

#36 feat: extend stacks for hooks and actor
  go.mod
  go.sum
  internal/resource/infrastructure_stack.go
  internal/resource/infrastructure_stack_model.go
  internal/resource/infrastructure_stack_schema.go
Labels: enhancement

#37 feat: Do not wait after helm install
  internal/resource/cluster_operator_handler.go
Labels: enhancement

#42 Fix plan modifier for cluster project id
  internal/resource/cluster_schema.go
Labels: bug, hotfix
