Repository pluralsh/terraform-provider-plural, pull requests merged in 2024-08, with the labels that each got.

#51 feat: add stack run trigger resource
  docs/resources/stack_run_trigger.md
  example/stackruntrigger/main.tf
  go.mod
  go.sum
  internal/model/stack_run_trigger.go
  internal/provider/provider.go
  internal/resource/stack_run_trigger.go
Labels: enhancement

#52 Force reinstalls on k8s host changes
  internal/resource/cluster.go
  internal/resource/cluster_model.go
Labels: enhancement, hotfix

#55 fix: Fix polling logic in delete handlers
  internal/resource/cluster.go
  internal/resource/infrastructure_stack.go
  internal/resource/provider.go
  internal/resource/service_deployment.go
Labels: bug
